apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  namespace: wallet
spec:
  selector:
    app: wallet-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
